# 热部署
spring:
# 配置数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/galaxy?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: urnotFay1219
    driver-class-name: com.mysql.jdbc.Driver
    
  mybatis:
      configuration:
   #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
          map-underscore-to-camel-case: true

  logging:
      level:
   #打印SQL信息
         edu.unimelb.galaxyidentification.mapper: debug
          
  servlet:
    multipart:
    max-file-size: 1000MB
    max-request-size: 1000MB
      
  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/static/
      
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存
